//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int KullaniciID { get; set; }
        public string KullaniciAdi { get; set; }
        public int Sifre { get; set; }
        public int CalisanID { get; set; }
        public bool OnlineMİ { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Calisan Calisan { get; set; }
    }
}
