//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.YemekAraTablo = new HashSet<YemekAraTablo>();
        }
    
        public int SiparisID { get; set; }
        public int MasaID { get; set; }
        public int CalisanID { get; set; }
        public System.DateTime AlınmaZamani { get; set; }
        public int Durumu { get; set; }
        public Nullable<decimal> Tutari { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Calisan Calisan { get; set; }
        public virtual Masa Masa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YemekAraTablo> YemekAraTablo { get; set; }
    }
}
