//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YemekAraTablo
    {
        public int KayitID { get; set; }
        public int SiparisID { get; set; }
        public int YemekID { get; set; }
    
        public virtual Siparis Siparis { get; set; }
        public virtual Yemek Yemek { get; set; }
    }
}
